### GET DATA FOR ONE VISUALIZATION
GET http://localhost:5000/get/visudata/8/V5_Sectors

### GET SAVED DATA FOR CUSTOM VIEW
GET http://localhost:5000/get/customview/BXVmk9roiWQiCnalYyNL

### CHECK IF THE USER EXISTS OR NOT
//GET http://localhost:5000/auth/rw9o9LeXfxNIHAvXZwsExpszh4g2

### GET ALL THE USERS SAVED CUSTOM VIEWS
GET http://localhost:5000/all/customview/s3lfLHsYRhMBKxQc6kCbtSb4COl1

### DELETE SPECIFIC CUSTOM VIEW
DELETE http://localhost:5000/delete/customview/w00SedPsMqE969wqgLRx


### DELETE ALL THE USERS CUSTOM VIEWS
DELETE http://localhost:5000/deleteall/customview/EruPjCOkhvdEwhnuaLcKkiQT1f42





