### GET DATA FOR ONE VISUALIZATION
GET http://localhost:5000/get/visudata/8/V5_Sectors

### GET SAVED DATA FOR CUSTOM VIEW
GET http://localhost:5000/get/customview/BXVmk9roiWQiCnalYyNL

### CHECK IF THE USER EXISTS OR NOT
GET http://localhost:5000/auth/rw9o9LeXfxNIHAvXZwsExpszh4g2

### GET ALL THE USERS SAVED CUSTOM VIEWS
GET http://localhost:5000/all/customview/s3lfLHsYRhMBKxQc6kCbtSb4COl1

### DELETE USER
DELETE http://localhost:5000/deleteuser/sPPxE1n08iOZbygKiG8kP9sz3wm2

### DELETE SPECIFIC CUSTOM VIEW
DELETE http://localhost:5000/delete/customview/w00SedPsMqE969wqgLRx

### DELETE ALL THE USERS CUSTOM VIEWS
DELETE http://localhost:5000/deleteall/customview/NcTC3xH3E9bkVPPhwCgYODZyJtX2

### CREATE NEW CUSTOM VIEW
POST http://localhost:5000/create/customview
content-type: application/json

{
    "title": "Custom view created at Node",
    "user": "some-user-id",
    "viewText": "This comes from Node JS",
    "visuals": 
    {
        "v1": "true",
        "v2": "true",
        "v3": "false",
        "v4": "false",
        "v5": "true"
    }
}

### CREATE NEW USER
POST http://localhost:5000/createuser
content-type: application/json

{
    "email": "nodetest@testemail.com",
    "password": "123456",
    "firstName": "User",
    "lastName": "FromNode"
}

###LISÄTTY TÄNNE TESTIKOMMENTTI


